/* Generated by build.sh — edit the sources, not this file. */

/* ---- js/i18n.js ---- */
/* i18n — data-i18n sets textContent, data-i18n-aria-label sets aria-label. */

(function (window, document) {
  "use strict";

  var STORE_KEY = "halo.lang";
  var DEFAULT = "en";

  var DICT = {
    en: {
      "meta.title": "Halo — Smart Home Installation",
      "meta.description":
        "Wireless, modular smart home systems designed around how you actually live. No drilling, no complicated installation, no commitment to one address.",

      "nav.label": "Main",
      "lang.label": "Language",

      "hero.title": "A smarter home that fits your life.",
      "hero.body":
        "From lighting and climate to security and everyday routines, your smart home is designed around how you actually live.",
      "hero.cta": "Build My Smart Home",
      "hero.trust": "Wireless · Modular · Movable",

      "w.climate.room": "Living room",
      "w.climate.name": "Climate",
      "w.climate.note": "Holding 22.0 °C",

      "w.humidity.room": "Bedroom",
      "w.humidity.name": "Humidity",
      "w.humidity.note": "Comfortable range",

      "w.door.room": "Front door",
      "w.door.name": "Door sensor",
      "w.door.closed": "Closed",
      "w.door.open": "Open",
      "w.door.note": "Armed",
      "w.door.noteOpen": "Opened just now",

      "w.lights.room": "Hallway",
      "w.lights.name": "Lights",
      "w.lights.note": "Warm · 2700 K",

      "w.hub.name": "System online",
      "w.hub.note": "12 devices · 4 rooms",

      "w.link.reconnecting": "Reconnecting",
      "w.link.connected": "Connected",

      "w.leak.title": "Water leak detected",
      "w.leak.note": "Basement · water shut off automatically",

      "problem.eyebrow": "Right now",
      "problem.title": "You’re the automation.",
      "problem.lede":
        "Either you’re still flipping switches to find out which is which, or you’re four weekends into research with nothing installed.",

      "problem.a.label": "Wall by the front door",
      "problem.a.shot": "Unlabeled switches · a thermostat nobody trusts",
      "problem.a.quote": "“Which one’s the porch light again?”",
      "problem.a.stat": "14",
      "problem.a.statNote": "switches — 2 you can name",

      "problem.b.label": "Kitchen table, week three",
      "problem.b.shot": "Cables, opened hub boxes, spec sheets, too many tabs",
      "problem.b.quote": "“Do I need the hub, or does the app do it?”",
      "problem.b.stat": "47",
      "problem.b.statNote": "tabs — 0 in the cart",

      /* The far face of each cell. Only the toggle's accessible name is copy. */
      "problem.a.flipPhoto": "The wall by the front door, with Halo",
      "problem.a.flipQuote": "The porch light, with Halo",
      "problem.a.flipStat": "The switches, with Halo",
      "problem.a.shotAfter": "One plate · every room named",
      "problem.a.labelAfter": "Wall by the front door",
      "problem.a.quoteAfter": "“I haven’t touched a switch in a month.”",
      "problem.a.statAfter": "0",
      "problem.a.statNoteAfter": "switches left to guess at",

      "problem.b.flipPhoto": "The kitchen table, with Halo",
      "problem.b.flipQuote": "The hub question, with Halo",
      "problem.b.flipStat": "The tabs, with Halo",
      "problem.b.shotAfter": "One box, one afternoon, nothing left to read",
      "problem.b.labelAfter": "Kitchen table, Thursday",
      "problem.b.quoteAfter": "“I still don’t know what a hub is.”",
      "problem.b.statAfter": "4h",
      "problem.b.statNoteAfter": "one visit, start to handover",

      /* Section 03 — each device is written once and read by its point and its card. */
      "plan.eyebrow": "Once it’s in",
      "plan.title": "The hardware disappears.",
      "plan.lede":
        "No new wall of switches, no tablet by the door. A dozen quiet devices you stop noticing by the second week — and a home that simply behaves.",
      "plan.hint.pointer": "Hover a point to see what is there",
      "plan.hint.touch": "Swipe the cards — the plan follows",
      "plan.photo":
        "Open-plan apartment: living room, kitchen and dining area by a wall of windows",
      "plan.note": "Two-bedroom loft · installed in one visit",

      "plan.media.pin": "Media, living room",
      "plan.media.room": "Living room",
      "plan.media.name": "TV & sound",
      "plan.media.state": "Standby",
      "plan.media.note": "One tap for cinema",

      "plan.hub.pin": "Hub, hallway",
      "plan.hub.room": "Hallway",
      "plan.hub.name": "Hub",
      "plan.hub.state": "Online",
      "plan.hub.note": "12 devices · 4 rooms",

      "plan.climate.pin": "Climate, living room",
      "plan.climate.room": "Living room",
      "plan.climate.name": "Climate",
      "plan.climate.value": "21.8",
      "plan.climate.note": "Holding 22.0 °C",

      "plan.lights.pin": "Ceiling lights, living room",
      "plan.lights.room": "Living room",
      "plan.lights.name": "Ceiling lights",
      "plan.lights.note": "Evening scene · 2700 K",

      "plan.lock.pin": "Smart lock, entry",
      "plan.lock.room": "Entry",
      "plan.lock.name": "Smart lock",
      "plan.lock.state": "Locked",
      "plan.lock.note": "Locks behind you",

      "plan.presence.pin": "Presence sensor, hallway",
      "plan.presence.room": "Hallway",
      "plan.presence.name": "Presence sensor",
      "plan.presence.state": "Clear",
      "plan.presence.note": "The light finds you",

      "plan.leak.pin": "Leak sensor, kitchen",
      "plan.leak.room": "Kitchen",
      "plan.leak.name": "Leak sensor",
      "plan.leak.state": "Dry",
      "plan.leak.note": "The valve closes on its own",

      "plan.shades.pin": "Shades, dining area",
      "plan.shades.room": "Dining area",
      "plan.shades.name": "Shades",
      "plan.shades.note": "Closing at sunset",

      /* Section 04 — the same system at four devices; readings match section 03. */
      "grow.eyebrow": "Start small",
      "grow.title": "Nobody starts with the whole house.",
      "grow.lede":
        "The hub goes in first. Everything after it is a decision you make later — one room at a time, in any order, whenever it suits you.",

      "grow.hub.room": "Hallway",
      "grow.hub.name": "Hub",
      "grow.hub.state": "Online",
      "grow.hub.note": "One room · four devices",

      "grow.lights.room": "Living room",
      "grow.lights.name": "Ceiling lights",
      "grow.lights.note": "Evening scene · 2700 K",

      "grow.climate.room": "Living room",
      "grow.climate.name": "Climate",
      "grow.climate.value": "21.8",
      "grow.climate.note": "Holding 22.0 °C",

      "grow.lock.room": "Entry",
      "grow.lock.name": "Smart lock",
      "grow.lock.state": "Locked",
      "grow.lock.note": "Locks behind you",

      "grow.more": "Whatever comes next",
      "grow.aside.label": "Room to grow",
      "grow.aside.body":
        "Cameras, blinds, plugs, a sensor for the boiler — each one pairs itself to the hub that is already there. Nothing has to be bought twice.",

      /* Section 05 — the calculator. {placeholders} let a translation reorder them. */
      "calc.eyebrow": "What it costs",
      "calc.title": "A number before anyone comes round.",
      "calc.lede":
        "Three questions, and not one of them is an inventory of your windows. What comes back is a range — the same one we would quote you after a survey.",

      "calc.step": "Step {n} of {of}",
      "calc.left.2": "2 steps left",
      "calc.left.1": "1 step left",
      "calc.left.0": "last step",
      "calc.tick.1": "Vision",
      "calc.tick.2": "Scale",
      "calc.tick.3": "Details",

      "calc.s1.title": "What do you want to solve today?",
      "calc.s1.hint": "Pick as many as apply.",
      "calc.goal.security.name": "Feeling secure",
      "calc.goal.security.hint": "Doors, windows, locks, cameras, leaks, garage",
      "calc.goal.climate.name": "Climate that holds itself",
      "calc.goal.climate.hint": "Thermostat and room temperature",
      "calc.goal.light.name": "Light and shade",
      "calc.goal.light.hint": "Switches, color, LED strips, blinds",

      "calc.s2.title": "How much house are we covering?",
      "calc.s2.hint": "The footprint is enough — nobody is counting your windows.",
      "calc.home.flat.name": "Apartment / Condo",
      "calc.home.flat.hint": "1–2 bedrooms",
      "calc.home.town.name": "Townhouse",
      "calc.home.town.hint": "2–3 bedrooms",
      "calc.home.house.name": "Single family home",
      "calc.home.house.hint": "3+ bedrooms",

      "calc.s3.title": "Anything that changes the count?",
      "calc.s3.hint":
        "Optional. The numbers already there are typical for the home you picked.",
      "calc.doors.label": "How many exterior doors do you have?",
      "calc.temp.label": "How many rooms need their own reading?",
      "calc.lights.label": "How many rooms get light control?",
      "calc.lawn.label": "Lawn watering",
      "calc.lawn.hint": "One controller, zoned across the lawn and the beds",

      "calc.back": "Back",
      "calc.next": "Continue",
      "calc.see": "See my estimate",

      "calc.result.label": "Your estimate",
      "calc.result.to": "to",
      "calc.result.pkg": "Package",
      "calc.result.home": "Home",
      "calc.result.tax": "+ tax",
      "calc.result.note":
        "This is an estimate. We create your personalized list before starting a project where you can remove or add items.",

      /* The bill: one line per kind of device, then the work, the one line in %. */
      "calc.item.hub": "Hub",
      "calc.item.contact": "Door and window sensors",
      "calc.item.lock": "Smart locks",
      "calc.item.camera": "Cameras",
      "calc.item.leak": "Leak sensors",
      "calc.item.garage": "Garage door controllers",
      "calc.item.thermostat": "Thermostat",
      "calc.item.temp": "Temperature sensors",
      "calc.item.control": "Light switches",
      "calc.item.bulb": "Color bulbs and LED strips",
      "calc.item.blind": "Blind controllers",
      "calc.item.lawn": "Watering controller",
      "calc.item.valve": "Water valves",
      "calc.item.work": "Installation, setup and handover",
      "calc.cta": "Email the Professional",
      "calc.again": "Adjust answers",

      /* The goals, in the order step one asks them; all three become one name. */
      "calc.pkg.security": "Security",
      "calc.pkg.climate": "Climate",
      "calc.pkg.light": "Light",
      "calc.pkg.join": " & ",
      "calc.pkg.all": "Whole Home",

      "calc.home.flat.full": "1–2 Bedroom Apartment",
      "calc.home.town.full": "2–3 Bedroom Townhouse",
      "calc.home.house.full": "3+ Bedroom Home",

      "calc.mail.subject": "Quote Request: {range} Smart Home",
      "calc.mail.body":
        "Hi team, I just used the calculator on your site. I'm interested in the {package} package for my {home}. The estimated range was {range}. I'd love to get a detailed breakdown and hardware list. Let me know the next steps!",

      "calc.unique": "Have a unique project?",
      "calc.unique.link": "Email us",

      /* Section 06 — the process. "About an hour" is an assumption, unlike the rest. */
      "flow.eyebrow": "How it goes",
      "flow.title": "Three steps, about two weeks.",
      "flow.lede":
        "One conversation to decide what goes in, one payment to order it, one visit to put it up. The only waiting is the shipping.",

      "flow.s1.title": "Consultation",
      "flow.s1.body":
        "We go through the place together and come out with one list of devices that fits the house, the way you live in it and what you want to spend. The range from the calculator becomes a list and a number.",
      "flow.s1.footLabel": "Takes",
      "flow.s1.footValue": "about an hour",

      "flow.s2.title": "Prepayment",
      "flow.s2.body":
        "Nothing sits waiting in a warehouse: every kit is ordered for its own project, so the hardware is paid for up front. That is what puts the order in.",
      "flow.s2.footLabel": "Then",
      "flow.s2.footValue": "ordered the same day",

      "flow.wait.value": "≈ 2 weeks",
      "flow.wait.body":
        "Delivery. Nothing is needed from you in here — we tell you the day it lands and book the install around your week.",

      "flow.s3.title": "Installation",
      "flow.s3.body":
        "One visit. Everything is mounted, paired, named and tested, and then we walk you through it — four hours for an apartment, up to eight for a house.",
      "flow.s3.footLabel": "On site",
      "flow.s3.footValue": "4–8 hours",

      "flow.done.title": "And that is all.",
      "flow.done.body": "A house that works, and nothing left on your list.",

      /* Section 07 — the year of support is the only new claim, and narrow on purpose. */
      "adapt.eyebrow": "After handover",
      "adapt.title": "Nothing here is set in stone.",
      "adapt.lede":
        "You can add to it, you can take it with you — and for the first year we keep it running so you do not have to think about it.",

      "adapt.add.title": "Add whatever comes next",
      "adapt.add.body":
        "A camera, blinds, a sensor for the boiler. Each one pairs itself to the hub that is already there, in any order, whenever it suits you — and nothing already installed has to be bought again.",

      "adapt.move.title": "It unplugs",
      "adapt.move.body":
        "Nothing is chased into a wall and nothing is drilled. The system comes off in an afternoon and goes back up at the next address: the same hub, the same devices, the same routines.",

      "adapt.year.label": "Lifestyle adaptation",
      "adapt.year.badge": "Included · first year",
      "adapt.year.title": "12 months of support included.",
      "adapt.year.body":
        "Not a call center. The person who set your system up, on the other end of it.",

      /* Lead-in and sentence are two keys: the dictionary holds text, not markup. */
      "adapt.year.a.lead": "Anything you add, we set up.",
      "adapt.year.a.body":
        "Buy a device later and we pair it, name it and put it into the routines that already run.",
      "adapt.year.b.lead": "Batteries before they die.",
      "adapt.year.b.body":
        "We watch which sensors are getting low and change them, so you never meet a dead one.",
      "adapt.year.c.lead": "A message, not a ticket.",
      "adapt.year.c.body":
        "If something is behaving oddly we look at the system from here, and usually fix it without coming round.",

      "adapt.dim.from": "Handover",
      "adapt.dim.to": "12 months",

      /* Section 08 — brand names stay untranslated; only the frame around them moves. */
      "trust.eyebrow": "What goes in",
      "trust.title": "We build on Aqara.",
      "trust.lede":
        "One manufacturer, so every device in the house pairs the same way and answers to the same hub.",
      "trust.brandNote": "the hardware we install",
      "trust.railLabel": "Works with",
      "trust.note":
        "Every name and mark above belongs to its owner, and is shown only to say what the system connects to.",

      /* Section 09 — the objections the page has not answered anywhere above. */
      "faq.eyebrow": "Before you ask",
      "faq.title": "The rest of the questions.",
      "faq.lede":
        "The page has answered the big ones. These are the six that come up on the phone afterwards.",

      "faq.q1": "Does any of it stop working when the internet does?",
      "faq.a1":
        "The hub runs the house, not a server somewhere else. Switches, sensors, lights and the routines between them carry on through an outage, because none of it ever left the building. What goes until the line is back is the app from outside, and the notifications on your phone.",

      "faq.q2": "Do I have to use my phone for everything?",
      "faq.a2":
        "No. Every light keeps a switch on the wall and every switch still does the obvious thing, so the house works for somebody who has never opened the app. The phone is for the house you are not standing in.",

      "faq.q3": "Is there a monthly fee?",
      "faq.a3":
        "No. You pay for the hardware and for the work, once. The year of support is part of the install rather than a plan you are put on, and nothing in the system asks for a subscription to keep running.",

      "faq.q4": "Can you use the devices I already own?",
      "faq.a4":
        "Often, yes — anything speaking Zigbee, Matter or Thread will usually join the hub and be named alongside the rest. We go through what you have at the consultation and say which of it is worth keeping: a device that half-works is worse than one you replaced.",

      "faq.q5": "Who can see the cameras and the sensors?",
      "faq.a5":
        "You can, on your own account. We are not in it — during the first year we look at the system when you ask us to, and that access is yours to take back whenever you like.",

      "faq.q6": "What happens if something breaks?",
      "faq.a6":
        "The hardware carries the manufacturer’s warranty and we make the claim, rather than sending you to a form. Inside the first year we come out and swap the device as part of the support the install came with.",

      "faq.ask": "Something that is not on the list?",
      "faq.ask.link": "Ask us directly",

      /* Section 10 — the close. The primary label is "hero.cta", not a copy of it. */
      "cta.eyebrow": "Where to start",
      "cta.title": "Three questions, and a number.",
      "cta.lede":
        "It is three questions long. What comes back is a range, the list of hardware behind it, and a letter you can read and edit before it goes anywhere.",
      "cta.secondary": "Talk to us first",
      "cta.note": "≈ 1 minute · no account · nothing is posted anywhere",

      /* The footer, on every page. The year is written out — one edit a year,
         one key per language. */
      "foot.navLabel": "Footer",
      "foot.privacy": "Privacy Policy",
      "foot.note": "© 2026 Halo. All rights reserved.",

      /* Legal pages. "doc." is the frame, "privacy." is this one's contents. */
      "doc.back": "Back to the site",

      /* privacy.html. The policy itself is not written yet. */
      "privacy.meta.title": "Privacy Policy — Halo",
      "privacy.meta.description":
        "How Halo handles the information you share.",
      "privacy.eyebrow": "Legal",
      "privacy.title": "Privacy Policy"
    },

    ru: {
      "meta.title": "Halo — Установка умного дома",
      "meta.description":
        "Беспроводные модульные системы умного дома, собранные под то, как вы действительно живёте. Без сверления, без сложной установки, без привязки к одному адресу.",

      "nav.label": "Основная навигация",
      "lang.label": "Язык",

      "hero.title": "Умный дом, который подстраивается под вашу жизнь.",
      "hero.body":
        "Освещение, климат, безопасность и повседневные сценарии — всё создаётся с учётом того, как вы действительно живёте.",
      "hero.cta": "Собрать мой умный дом",
      "hero.trust": "Беспроводной · Модульный · Переносимый",

      "w.climate.room": "Гостиная",
      "w.climate.name": "Климат",
      "w.climate.note": "Держит 22,0 °C",

      "w.humidity.room": "Спальня",
      "w.humidity.name": "Влажность",
      "w.humidity.note": "Комфортный уровень",

      "w.door.room": "Входная дверь",
      "w.door.name": "Датчик двери",
      "w.door.closed": "Закрыто",
      "w.door.open": "Открыто",
      "w.door.note": "Под охраной",
      "w.door.noteOpen": "Только что открыли",

      "w.lights.room": "Прихожая",
      "w.lights.name": "Свет",
      "w.lights.note": "Тёплый · 2700 K",

      "w.hub.name": "Система на связи",
      "w.hub.note": "12 устройств · 4 зоны",

      "w.link.reconnecting": "Переподключение",
      "w.link.connected": "Подключено",

      "w.leak.title": "Обнаружена протечка",
      "w.leak.note": "Подвал · вода перекрыта автоматически",

      "problem.eyebrow": "Пока что",
      "problem.title": "Автоматика в вашем доме — это вы.",
      "problem.lede":
        "Либо вы до сих пор щёлкаете выключателями наугад, либо четвёртые выходные читаете обзоры — а дома так ничего и не появилось.",

      "problem.a.label": "Стена у входной двери",
      "problem.a.shot": "Выключатели без подписей · термостат, которому не верят",
      "problem.a.quote": "«Какой из них свет на крыльце?»",
      "problem.a.stat": "14",
      "problem.a.statNote": "выключателей — 2 вы можете назвать",

      "problem.b.label": "Кухонный стол, третья неделя",
      "problem.b.shot": "Провода, вскрытые коробки хабов, спецификации, вкладки",
      "problem.b.quote": "«А хаб вообще нужен, или всё через приложение?»",
      "problem.b.stat": "47",
      "problem.b.statNote": "вкладок — 0 в корзине",

      "problem.a.flipPhoto": "Стена у входной двери — с Halo",
      "problem.a.flipQuote": "Свет на крыльце — с Halo",
      "problem.a.flipStat": "Выключатели — с Halo",
      "problem.a.shotAfter": "Одна панель · у каждой комнаты есть имя",
      "problem.a.labelAfter": "Стена у входной двери",
      "problem.a.quoteAfter": "«Уже месяц не подхожу к выключателям.»",
      "problem.a.statAfter": "0",
      "problem.a.statNoteAfter": "выключателей, которые надо угадывать",

      "problem.b.flipPhoto": "Кухонный стол — с Halo",
      "problem.b.flipQuote": "Вопрос про хаб — с Halo",
      "problem.b.flipStat": "Вкладки — с Halo",
      "problem.b.shotAfter": "Одна коробка, один день, читать больше нечего",
      "problem.b.labelAfter": "Кухонный стол, четверг",
      "problem.b.quoteAfter": "«Я до сих пор не знаю, что такое хаб.»",
      "problem.b.statAfter": "4 ч",
      "problem.b.statNoteAfter": "один визит — от начала до сдачи",

      "plan.eyebrow": "Когда всё уже стоит",
      "plan.title": "Оборудование исчезает.",
      "plan.lede":
        "Ни новой стены выключателей, ни планшета у двери. Десяток незаметных устройств, которые перестаёшь замечать на вторую неделю, — и дом, который просто работает.",
      "plan.hint.pointer": "Наведите на точку — увидите устройство",
      "plan.hint.touch": "Листайте карточки — план следует за ними",
      "plan.photo":
        "Квартира со свободной планировкой: гостиная, кухня и столовая у панорамных окон",
      "plan.note": "Двухкомнатный лофт · установка за один визит",

      "plan.media.pin": "Медиа, гостиная",
      "plan.media.room": "Гостиная",
      "plan.media.name": "ТВ и звук",
      "plan.media.state": "Ожидание",
      "plan.media.note": "Кино — одним касанием",

      "plan.hub.pin": "Хаб, прихожая",
      "plan.hub.room": "Прихожая",
      "plan.hub.name": "Хаб",
      "plan.hub.state": "На связи",
      "plan.hub.note": "12 устройств · 4 зоны",

      "plan.climate.pin": "Климат, гостиная",
      "plan.climate.room": "Гостиная",
      "plan.climate.name": "Климат",
      "plan.climate.value": "21,8",
      "plan.climate.note": "Держит 22,0 °C",

      "plan.lights.pin": "Потолочный свет, гостиная",
      "plan.lights.room": "Гостиная",
      "plan.lights.name": "Потолочный свет",
      "plan.lights.note": "Вечерний сценарий · 2700 K",

      "plan.lock.pin": "Умный замок, вход",
      "plan.lock.room": "Вход",
      "plan.lock.name": "Умный замок",
      "plan.lock.state": "Заперто",
      "plan.lock.note": "Закроется за вами",

      "plan.presence.pin": "Датчик присутствия, прихожая",
      "plan.presence.room": "Прихожая",
      "plan.presence.name": "Датчик присутствия",
      "plan.presence.state": "Никого",
      "plan.presence.note": "Свет находит вас сам",

      "plan.leak.pin": "Датчик протечки, кухня",
      "plan.leak.room": "Кухня",
      "plan.leak.name": "Датчик протечки",
      "plan.leak.state": "Сухо",
      "plan.leak.note": "Кран перекроется сам",

      "plan.shades.pin": "Шторы, столовая",
      "plan.shades.room": "Столовая",
      "plan.shades.name": "Шторы",
      "plan.shades.note": "Закроются на закате",

      "grow.eyebrow": "Начните с малого",
      "grow.title": "Никто не начинает со всего дома.",
      "grow.lede":
        "Сначала ставится хаб. Всё остальное — решения, которые можно принять потом: по одной комнате, в любом порядке и тогда, когда вам удобно.",

      "grow.hub.room": "Прихожая",
      "grow.hub.name": "Хаб",
      "grow.hub.state": "На связи",
      "grow.hub.note": "Одна комната · четыре устройства",

      "grow.lights.room": "Гостиная",
      "grow.lights.name": "Потолочный свет",
      "grow.lights.note": "Вечерний сценарий · 2700 K",

      "grow.climate.room": "Гостиная",
      "grow.climate.name": "Климат",
      "grow.climate.value": "21,8",
      "grow.climate.note": "Держит 22,0 °C",

      "grow.lock.room": "Вход",
      "grow.lock.name": "Умный замок",
      "grow.lock.state": "Заперто",
      "grow.lock.note": "Закроется за вами",

      "grow.more": "Что появится потом",
      "grow.aside.label": "Есть куда расти",
      "grow.aside.body":
        "Камеры, шторы, розетки, датчик у котла — каждое само подключается к уже стоящему хабу. Ничего не придётся покупать дважды.",

      "calc.eyebrow": "Сколько это стоит",
      "calc.title": "Цифра до того, как кто-то приедет.",
      "calc.lede":
        "Три вопроса — и ни одного о том, сколько у вас окон. В ответ вы получите вилку: ту же, что мы назвали бы после осмотра.",

      "calc.step": "Шаг {n} из {of}",
      "calc.left.2": "осталось 2 шага",
      "calc.left.1": "остался 1 шаг",
      "calc.left.0": "последний шаг",
      "calc.tick.1": "Цель",
      "calc.tick.2": "Масштаб",
      "calc.tick.3": "Детали",

      "calc.s1.title": "Что вы хотите решить сегодня?",
      "calc.s1.hint": "Выберите всё, что подходит.",
      "calc.goal.security.name": "Спокойствие в доме",
      "calc.goal.security.hint": "Двери, окна, замки, камеры, протечки, гараж",
      "calc.goal.climate.name": "Климат, который держится сам",
      "calc.goal.climate.hint": "Термостат и температура по комнатам",
      "calc.goal.light.name": "Свет и шторы",
      "calc.goal.light.hint": "Выключатели, цвет, LED-ленты, шторы",

      "calc.s2.title": "Какой у вас дом?",
      "calc.s2.hint": "Достаточно общего масштаба — окна никто не считает.",
      "calc.home.flat.name": "Квартира",
      "calc.home.flat.hint": "1–2 спальни",
      "calc.home.town.name": "Таунхаус",
      "calc.home.town.hint": "2–3 спальни",
      "calc.home.house.name": "Отдельный дом",
      "calc.home.house.hint": "от 3 спален",

      "calc.s3.title": "Что-то, что меняет расчёт?",
      "calc.s3.hint":
        "Необязательно. Значения уже выставлены — типичные для выбранного дома.",
      "calc.doors.label": "Сколько у вас наружных дверей?",
      "calc.temp.label": "Скольким комнатам нужен свой датчик?",
      "calc.lights.label": "В скольких комнатах управлять светом?",
      "calc.lawn.label": "Полив газона",
      "calc.lawn.hint": "Один контроллер, по зонам: газон и грядки",

      "calc.back": "Назад",
      "calc.next": "Далее",
      "calc.see": "Показать оценку",

      "calc.result.label": "Ваша оценка",
      "calc.result.to": "до",
      "calc.result.pkg": "Пакет",
      "calc.result.home": "Дом",
      "calc.result.tax": "+ налог",
      "calc.result.note":
        "Это оценка. Перед стартом проекта мы соберём для вас персональный список — из него можно убрать позиции или добавить новые.",

      "calc.item.hub": "Хаб",
      "calc.item.contact": "Датчики дверей и окон",
      "calc.item.lock": "Умные замки",
      "calc.item.camera": "Камеры",
      "calc.item.leak": "Датчики протечки",
      "calc.item.garage": "Приводы гаражных ворот",
      "calc.item.thermostat": "Термостат",
      "calc.item.temp": "Датчики температуры",
      "calc.item.control": "Выключатели света",
      "calc.item.bulb": "Цветные лампы и LED-ленты",
      "calc.item.blind": "Приводы штор",
      "calc.item.lawn": "Контроллер полива",
      "calc.item.valve": "Клапаны полива",
      "calc.item.work": "Монтаж, настройка и сдача",
      "calc.cta": "Написать специалисту",
      "calc.again": "Изменить ответы",

      "calc.pkg.security": "Безопасность",
      "calc.pkg.climate": "Климат",
      "calc.pkg.light": "Свет",
      "calc.pkg.join": " и ",
      "calc.pkg.all": "Весь дом",

      "calc.home.flat.full": "квартира на 1–2 спальни",
      "calc.home.town.full": "таунхаус на 2–3 спальни",
      "calc.home.house.full": "дом от 3 спален",

      "calc.mail.subject": "Запрос сметы: умный дом {range}",
      "calc.mail.body":
        "Здравствуйте! Пользуюсь калькулятором на вашем сайте. Интересует пакет «{package}» для варианта «{home}». Оценка получилась {range}. Хочу получить подробный расчёт и список оборудования. Подскажите, какие дальше шаги!",

      "calc.unique": "Нестандартный проект?",
      "calc.unique.link": "Напишите нам",

      "flow.eyebrow": "Как это проходит",
      "flow.title": "Три шага и примерно две недели.",
      "flow.lede":
        "Один разговор, чтобы решить, что ставим, одна предоплата, чтобы это заказать, и один выезд, чтобы всё смонтировать. Ждать приходится только доставку.",

      "flow.s1.title": "Консультация",
      "flow.s1.body":
        "Проходим по дому вместе и выходим с одним списком устройств, который подходит и дому, и тому, как вы в нём живёте, и тому, сколько вы готовы потратить. Вилка из калькулятора превращается в список и одну сумму.",
      "flow.s1.footLabel": "Занимает",
      "flow.s1.footValue": "около часа",

      "flow.s2.title": "Предоплата",
      "flow.s2.body":
        "Ничего не лежит на складе: каждый комплект заказывается под свой проект, поэтому оборудование оплачивается заранее. Именно предоплата запускает заказ.",
      "flow.s2.footLabel": "Дальше",
      "flow.s2.footValue": "заказ в тот же день",

      "flow.wait.value": "≈ 2 недели",
      "flow.wait.body":
        "Доставка. Здесь от вас ничего не нужно — мы сообщим в день, когда всё придёт, и подберём день монтажа под вашу неделю.",

      "flow.s3.title": "Монтаж",
      "flow.s3.body":
        "Один выезд. Всё ставится, подключается, получает имя и проверяется, а потом мы показываем, как этим пользоваться, — четыре часа на квартиру и до восьми на дом.",
      "flow.s3.footLabel": "На месте",
      "flow.s3.footValue": "4–8 часов",

      "flow.done.title": "И это всё.",
      "flow.done.body":
        "Дом работает, а в вашем списке дел ничего не осталось.",

      "adapt.eyebrow": "После сдачи",
      "adapt.title": "Здесь ничто не сделано навсегда.",
      "adapt.lede":
        "Систему можно дополнить, её можно забрать с собой — а первый год мы сами следим за тем, чтобы она работала, и думать об этом не придётся.",

      "adapt.add.title": "Добавьте то, что появится потом",
      "adapt.add.body":
        "Камера, шторы, датчик у котла. Каждое устройство само подключается к уже стоящему хабу — в любом порядке и тогда, когда вам удобно, — а то, что уже стоит, покупать заново не нужно.",

      "adapt.move.title": "Она снимается",
      "adapt.move.body":
        "Ничего не спрятано в стену и ничего не просверлено. Система снимается за вечер и поднимается на новом адресе: тот же хаб, те же устройства, те же сценарии.",

      "adapt.year.label": "Адаптация под жизнь",
      "adapt.year.badge": "Включено · первый год",
      "adapt.year.title": "12 месяцев поддержки включены.",
      "adapt.year.body":
        "Никакого колл-центра. На связи тот же человек, который собрал вашу систему.",

      "adapt.year.a.lead": "Всё, что вы добавите, настроим мы.",
      "adapt.year.a.body":
        "Купите устройство позже — мы его подключим, назовём и впишем в сценарии, которые уже работают.",
      "adapt.year.b.lead": "Батарейки — до того, как они сядут.",
      "adapt.year.b.body":
        "Мы видим, у каких датчиков заряд на исходе, и меняем батарейки сами: разряженный датчик вам не встретится.",
      "adapt.year.c.lead": "Сообщение, а не заявка.",
      "adapt.year.c.body":
        "Если что-то ведёт себя странно, мы посмотрим систему отсюда и обычно починим, не приезжая.",

      "adapt.dim.from": "Сдача",
      "adapt.dim.to": "12 месяцев",

      "trust.eyebrow": "Что ставим",
      "trust.title": "Мы строим на Aqara.",
      "trust.lede":
        "Один производитель — значит, все устройства в доме подключаются одинаково и слушаются одного хаба.",
      "trust.brandNote": "оборудование, которое мы ставим",
      "trust.railLabel": "Работает с",
      "trust.note":
        "Все названия и знаки принадлежат их владельцам и показаны только чтобы обозначить совместимость.",

      "faq.eyebrow": "Прежде чем спросить",
      "faq.title": "Остальные вопросы.",
      "faq.lede":
        "На главные вопросы страница уже ответила. Эти шесть обычно задают потом, по телефону.",

      "faq.q1": "Что-нибудь перестанет работать, если пропадёт интернет?",
      "faq.a1":
        "Домом управляет хаб, а не сервер где-то далеко. Выключатели, датчики, свет и сценарии между ними переживают отключение, потому что ничто из этого дом и не покидало. До возвращения связи пропадают только приложение снаружи и уведомления на телефон.",

      "faq.q2": "Мне придётся всё делать с телефона?",
      "faq.a2":
        "Нет. У каждого светильника остаётся выключатель на стене, и каждый выключатель делает ровно то, что от него ждут: дом работает и для того, кто ни разу не открывал приложение. Телефон нужен для дома, в котором вас сейчас нет.",

      "faq.q3": "Есть ли ежемесячная плата?",
      "faq.a3":
        "Нет. Вы платите за оборудование и за работу — один раз. Год поддержки входит в установку, а не в тариф, на который вас подписали, и ничто в системе не требует подписки, чтобы работать.",

      "faq.q4": "Можно ли использовать устройства, которые у меня уже есть?",
      "faq.a4":
        "Часто да: всё, что говорит на Zigbee, Matter или Thread, обычно подключается к хабу и получает имя наравне с остальным. На консультации мы разберём, что у вас есть, и скажем, что стоит оставить: устройство, работающее наполовину, хуже заменённого.",

      "faq.q5": "Кто видит камеры и датчики?",
      "faq.a5":
        "Вы — в своей учётной записи. Нас в ней нет: в течение первого года мы смотрим систему, когда вы сами об этом просите, и этот доступ вы вправе забрать в любой момент.",

      "faq.q6": "Что будет, если что-то сломается?",
      "faq.a6":
        "На оборудование действует гарантия производителя, и обращаемся по ней мы, а не отправляем вас заполнять форму. В первый год мы приезжаем и меняем устройство — это часть поддержки, которая идёт вместе с установкой.",

      "faq.ask": "Не нашли своего вопроса?",
      "faq.ask.link": "Спросите нас напрямую",

      "cta.eyebrow": "С чего начать",
      "cta.title": "Три вопроса — и цифра.",
      "cta.lede":
        "Калькулятор выше — это три вопроса. В ответ вы получаете диапазон, список оборудования за ним и письмо, которое можно прочитать и поправить, прежде чем оно куда-то уйдёт.",
      "cta.secondary": "Сначала поговорить",
      "cta.note": "≈ 1 минута · без регистрации · никуда ничего не отправляется",

      "foot.navLabel": "Подвал сайта",
      "foot.privacy": "Политика конфиденциальности",
      "foot.note": "© 2026 Halo. Все права защищены.",

      "doc.back": "Вернуться на сайт",

      "privacy.meta.title": "Политика конфиденциальности — Halo",
      "privacy.meta.description":
        "Как Halo обращается с данными, которые вы передаёте.",
      "privacy.eyebrow": "Правовая информация",
      "privacy.title": "Политика конфиденциальности"
    }
  };

  function stored() {
    try {
      return window.localStorage.getItem(STORE_KEY);
    } catch (e) {
      return null;
    }
  }

  function remember(lang) {
    try {
      window.localStorage.setItem(STORE_KEY, lang);
    } catch (e) {
      /* private mode — the page still works, it just forgets. */
    }
  }

  function fromSystem() {
    var langs = window.navigator.languages || [window.navigator.language || ""];
    for (var i = 0; i < langs.length; i++) {
      var tag = String(langs[i]).toLowerCase();
      if (tag.indexOf("ru") === 0) return "ru";
      if (tag.indexOf("en") === 0) return "en";
    }
    return DEFAULT;
  }

  var current = DICT[stored()] ? stored() : fromSystem();

  function t(key) {
    var table = DICT[current] || DICT[DEFAULT];
    return Object.prototype.hasOwnProperty.call(table, key) ? table[key] : key;
  }

  /* Translate a subtree in place: on load, on a switch, and after any runtime write. */
  function apply(root) {
    var scope = root || document;

    if (scope === document) {
      /* A page names its own title and description keys on <html>; the landing
         page names neither and gets the defaults. */
      var root = document.documentElement;
      root.lang = current;
      document.title = t(root.getAttribute("data-meta-title") || "meta.title");
      var meta = document.querySelector('meta[name="description"]');
      if (meta) {
        meta.setAttribute(
          "content",
          t(root.getAttribute("data-meta-desc") || "meta.description")
        );
      }
    }

    var nodes = scope.querySelectorAll("[data-i18n]");
    for (var i = 0; i < nodes.length; i++) {
      nodes[i].textContent = t(nodes[i].getAttribute("data-i18n"));
    }
    if (scope.nodeType === 1 && scope.hasAttribute("data-i18n")) {
      scope.textContent = t(scope.getAttribute("data-i18n"));
    }

    var labeled = scope.querySelectorAll("[data-i18n-aria-label]");
    for (var j = 0; j < labeled.length; j++) {
      labeled[j].setAttribute(
        "aria-label",
        t(labeled[j].getAttribute("data-i18n-aria-label"))
      );
    }
  }

  function set(lang) {
    if (!DICT[lang] || lang === current) return;
    current = lang;
    remember(lang);
    apply(document);
    syncSwitch();
    document.dispatchEvent(
      new CustomEvent("halo:langchange", { detail: { lang: current } })
    );
  }

  function syncSwitch() {
    var buttons = document.querySelectorAll(".langswitch [data-lang]");
    for (var i = 0; i < buttons.length; i++) {
      buttons[i].setAttribute(
        "aria-pressed",
        buttons[i].getAttribute("data-lang") === current ? "true" : "false"
      );
    }
  }

  document.addEventListener("click", function (event) {
    var button = event.target.closest(".langswitch [data-lang]");
    if (button) set(button.getAttribute("data-lang"));
  });

  window.Halo = window.Halo || {};
  window.Halo.i18n = {
    t: t,
    set: set,
    apply: apply,
    get lang() {
      return current;
    }
  };

  apply(document);
  syncSwitch();
})(window, document);

/* ---- js/reveal.js ---- */
/* Reveal — hold a [data-reveal] section's [data-anim] entrance until it scrolls in. */

(function (window, document) {
  "use strict";

  var sections = document.querySelectorAll("[data-reveal]");
  if (!sections.length) return;

  var reduced = window.matchMedia("(prefers-reduced-motion: reduce)");
  if (reduced.matches || !("IntersectionObserver" in window)) return;

  var observer = new window.IntersectionObserver(
    function (entries) {
      for (var i = 0; i < entries.length; i++) {
        if (!entries[i].isIntersecting) continue;
        entries[i].target.setAttribute("data-reveal", "in");
        observer.unobserve(entries[i].target);
      }
    },
    /* A sliver is not enough: the entrance would be half over before it is worth seeing. */
    { threshold: 0.15 }
  );

  /* Set here, never in markup: without JS or with reduced motion nothing pauses. */
  for (var i = 0; i < sections.length; i++) {
    sections[i].setAttribute("data-reveal", "out");
    observer.observe(sections[i]);
  }
})(window, document);

/* ---- js/problem.js ---- */
/* Problem — click a cell to flip its two faces; the corner toggle is the real control. */

(function (window, document) {
  "use strict";

  var section = document.querySelector(".problem");
  if (!section) return;

  var cells = section.querySelectorAll("[data-flip]");
  if (!cells.length) return;

  /* CSS hides the far face visually only, so the aria pair is kept in step here. */
  function paint(cell, on) {
    cell.classList.toggle("is-flipped", on);

    var toggle = cell.querySelector("[data-flip-toggle]");
    if (toggle) toggle.setAttribute("aria-pressed", on ? "true" : "false");

    var front = cell.querySelector(".problem__face--front");
    var back = cell.querySelector(".problem__face--back");
    if (front) front.setAttribute("aria-hidden", on ? "true" : "false");
    if (back) back.setAttribute("aria-hidden", on ? "false" : "true");
  }

  /* Selecting a line of the quote should not also turn the card over. */
  function selecting() {
    var selection = window.getSelection();
    return !!selection && String(selection).length > 0;
  }

  for (var i = 0; i < cells.length; i++) {
    paint(cells[i], false);

    /* One listener per cell; the toggle's click bubbles here, so the two cannot disagree. */
    cells[i].addEventListener("click", function (event) {
      if (selecting()) return;
      var cell = event.currentTarget;
      paint(cell, !cell.classList.contains("is-flipped"));
    });
  }
})(window, document);

/* ---- js/plan.js ---- */
/* Plan — pairs each photo point with its rail card by data-device, one open at a time. */

(function (window, document) {
  "use strict";

  var section = document.querySelector(".plan");
  if (!section) return;

  var rail = section.querySelector("[data-plan-rail]");
  var pins = section.querySelectorAll(".plan__pin[data-device]");
  if (!rail || !pins.length) return;

  var GRACE = 140; /* ms the pointer may spend crossing from a point to its card */

  var devices = [];
  var open = null; /* the device showing its card, above the breakpoint */
  var held = false; /* opened by a click rather than by the pointer */
  var closing = null;

  for (var i = 0; i < pins.length; i++) {
    var pin = pins[i];
    var name = pin.getAttribute("data-device");
    var slot = rail.querySelector('.plan__slot[data-device="' + name + '"]');
    if (!slot) continue;

    /* The place is written on the pin only; the card gets a copy, never a repeat. */
    slot.style.setProperty("--x", pin.style.getPropertyValue("--x"));
    slot.style.setProperty("--y", pin.style.getPropertyValue("--y"));
    slot.setAttribute("data-place", pin.getAttribute("data-place") || "above");
    slot.setAttribute("data-align", pin.getAttribute("data-align") || "center");

    devices.push({
      pin: pin,
      slot: slot,
      dot: pin.querySelector(".plan__dot"),
      left: 0, /* filled by measure(); rail-content coordinates, not viewport */
      width: 0
    });
  }
  if (!devices.length) return;

  /* Which layout is running. Must stay in step with the .plan__rail breakpoint in
     sections.css — the one place the value is duplicated outside the stylesheet. */
  var PINNED_AT = "(min-width: 900px)";
  var query = window.matchMedia(PINNED_AT);
  var pinned = query.matches;

  /* ---- Above the breakpoint: one card open at its point ----------------- */

  function show(device) {
    window.clearTimeout(closing);
    if (open === device) return;
    if (open) paint(open, false);
    open = device;
    paint(device, true);
  }

  function hide(now) {
    window.clearTimeout(closing);
    if (!open) return;
    if (now) {
      paint(open, false);
      open = null;
      held = false;
      return;
    }
    closing = window.setTimeout(function () {
      if (!held && open) {
        paint(open, false);
        open = null;
      }
    }, GRACE);
  }

  function paint(device, on) {
    device.slot.classList.toggle("is-open", on);
    device.pin.classList.toggle("is-active", on);
    if (pinned) device.dot.setAttribute("aria-expanded", on ? "true" : "false");
  }

  /* ---- Under the breakpoint: the centered card owns its point ------------ */

  var frame = 0;
  var railMid = 0;

  /* The rail scrolls but its cards never move within it, so their places hold until
     the viewport changes. Measured in one batch so scan() can be all reads-then-writes.

     The origin has to be normalised: the entrance animation puts a transform on the
     rail, which makes it the offsetParent, and `rise` ends at transform:none, which
     hands that role back to .plan__stage. Same card, two different offsetLeft values. */
  function measure() {
    railMid = rail.clientWidth / 2;

    for (var i = 0; i < devices.length; i++) {
      var slot = devices[i].slot;
      var base = slot.offsetParent === rail ? 0 : rail.offsetLeft + rail.clientLeft;
      devices[i].left = slot.offsetLeft - base;
      devices[i].width = slot.offsetWidth;
    }
  }

  /* Where the rail's centre sits in card coordinates, in the cards' own units. */
  function centre() {
    return rail.scrollLeft + railMid;
  }

  function scan() {
    frame = 0;
    if (pinned) return;

    var middle = centre();
    var nearest = null;
    var shortest = Infinity;

    for (var i = 0; i < devices.length; i++) {
      var away = Math.abs(devices[i].left + devices[i].width / 2 - middle);
      if (away < shortest) {
        shortest = away;
        nearest = devices[i];
      }
    }

    for (var j = 0; j < devices.length; j++) {
      var is = devices[j] === nearest;
      devices[j].slot.classList.toggle("is-active", is);
      devices[j].pin.classList.toggle("is-active", is);
    }
  }

  /* One scan per frame; replace the pending one so a frame that never comes cannot stick. */
  function rescan() {
    window.cancelAnimationFrame(frame);
    frame = window.requestAnimationFrame(scan);
  }

  /* ---- Wiring ------------------------------------------------------------ */

  for (var k = 0; k < devices.length; k++) {
    (function (device) {
      device.pin.addEventListener("mouseenter", function () {
        if (pinned && !held) show(device);
      });
      device.pin.addEventListener("mouseleave", function () {
        if (pinned && !held) hide();
      });
      /* Hovering the card holds it open, or it shuts as the pointer reaches it. */
      device.slot.addEventListener("mouseenter", function () {
        if (pinned && !held) show(device);
      });
      device.slot.addEventListener("mouseleave", function () {
        if (pinned && !held) hide();
      });

      /* The keyboard gets the same card, without the grace period. */
      device.dot.addEventListener("focus", function () {
        if (pinned) show(device);
      });
      device.dot.addEventListener("blur", function () {
        if (pinned && !held) hide(true);
      });

      device.dot.addEventListener("click", function () {
        if (!pinned) {
          /* Center the card by hand: scrollIntoView would also drag the photo off screen.
             Off the same cache as scan(), or the snapped card and the lit one can differ. */
          rail.scrollBy({
            left: device.left + device.width / 2 - centre(),
            behavior: "smooth"
          });
          return;
        }
        if (open === device && held) {
          held = false;
          hide(true);
        } else {
          held = false;
          show(device);
          held = true;
        }
      });
    })(devices[k]);
  }

  /* A card held open by a click is dismissed the way anything else is. */
  document.addEventListener("click", function (event) {
    if (!held) return;
    if (event.target.closest(".plan__pin, .plan__slot")) return;
    held = false;
    hide(true);
  });
  document.addEventListener("keydown", function (event) {
    if (event.key !== "Escape" || !open) return;
    var dot = open.dot;
    held = false;
    hide(true);
    dot.focus();
  });

  rail.addEventListener("scroll", rescan, { passive: true });

  /* Above the breakpoint nothing is centered, so the scan's marks would stick. */
  function clear() {
    hide(true);
    for (var i = 0; i < devices.length; i++) {
      devices[i].slot.classList.remove("is-active");
      devices[i].pin.classList.remove("is-active");
    }
  }

  /* The only place pinned is written. Re-read here rather than trusting the change
     event alone, so a missed one cannot strand the layout in the wrong mode;
     query.matches is a cached flag, not a style recalc like getComputedStyle was. */
  function relayout() {
    pinned = query.matches;
    /* Under the breakpoint every card is already on the rail, so a point expands
       nothing — it scrolls. Carrying aria-expanded there would say the opposite. */
    for (var i = 0; i < devices.length; i++) {
      if (pinned) devices[i].dot.setAttribute("aria-expanded", "false");
      else devices[i].dot.removeAttribute("aria-expanded");
    }
    if (pinned) {
      clear();
      return;
    }
    measure();
    rescan();
  }

  /* addListener is the Safari < 14 spelling, and this file still carries ES5. */
  if (query.addEventListener) query.addEventListener("change", relayout);
  else query.addListener(relayout);

  window.addEventListener("resize", relayout);

  /* The places now change only here, never mid-scroll. The rail alone is enough: its
     height follows the tallest card, so a root font-size change — which moves the cards
     by shifting the rem gaps, without touching any width — still comes through. */
  if (window.ResizeObserver) {
    var watcher = new window.ResizeObserver(function () {
      if (pinned) return;
      measure();
      rescan();
    });
    watcher.observe(rail);
  }

  /* Set here, never in markup: with no script the cards stay a plain readable rail. */
  section.setAttribute("data-plan", "live");
  relayout();
})(window, document);

/* ---- js/hero.js ---- */
/* Hero — drifting readings, plus door, leak and hub events taking turns on one script. */

(function (window, document) {
  "use strict";

  var hero = document.querySelector(".hero");
  if (!hero) return;

  var i18n = (window.Halo && window.Halo.i18n) || null;
  /* Reduced motion drops the events; the readings drift on — a number is not motion. */
  var reduced = window.matchMedia("(prefers-reduced-motion: reduce)");
  var beats = [];

  function rand(min, max) {
    return min + Math.random() * (max - min);
  }

  /* One event at a time, each with its own gap. Pushed in the order they play. */
  var script = [];
  var FIRST = 5000; /* after the entrance has finished */
  var GAP = 4000; /* the quiet between one event ending and the next */
  var LOOP = 6000; /* the longer quiet before the script starts over */

  function runner() {
    var timer = null;
    var step = -1;

    function stopAll() {
      for (var i = 0; i < script.length; i++) script[i].hide();
    }

    function wait(ms) {
      window.clearTimeout(timer);
      timer = window.setTimeout(play, ms);
    }

    function play() {
      step = (step + 1) % script.length;
      var current = script[step];
      current.show();
      timer = window.setTimeout(function () {
        current.hide();
        wait(step === script.length - 1 ? LOOP : GAP);
      }, current.hold);
    }

    var api = {
      start: function () {
        wait(FIRST);
      },
      stop: function () {
        window.clearTimeout(timer);
        stopAll();
        step = -1;
      }
    };
    beats.push(api);
    return api;
  }

  /* A beat with nothing to put away — it just ticks. */
  function tick(config) {
    var timer = null;

    function run() {
      if (!document.hidden) config.step();
      timer = window.setTimeout(run, config.period());
    }

    var api = {
      start: function () {
        timer = window.setTimeout(run, config.first);
      },
      stop: function () {
        window.clearTimeout(timer);
      }
    };
    beats.push(api);
    return api;
  }

  /* Swap a reading without it snapping — fade down, change, fade back. */
  function reveal(node, write) {
    var reading = node.closest("[data-reading]");
    if (!reading) {
      write();
      return;
    }
    reading.classList.add("is-changing");
    window.setTimeout(function () {
      write();
      reading.classList.remove("is-changing");
    }, 200);
  }

  /* ---- Climate: a slow wander around the target ------------------------- */

  var tempNode = hero.querySelector("[data-temp]");
  var temp = 21.5;

  function paintTemp() {
    if (!tempNode) return;
    var text = temp.toFixed(1);
    tempNode.textContent =
      i18n && i18n.lang === "ru" ? text.replace(".", ",") : text;
  }

  if (tempNode) {
    /* Markup carries the English form; paint before the first drift or ru shows "21.5". */
    paintTemp();

    tick({
      first: 6000,
      period: function () {
        return rand(7000, 11000);
      },
      step: function () {
        var next = temp + (Math.random() < 0.5 ? -0.1 : 0.1);
        if (next < 21.1 || next > 21.9) next = temp - (next - temp);
        temp = Math.round(next * 10) / 10;
        reveal(tempNode, paintTemp);
      }
    });
  }

  /* ---- Humidity: the same wander, plus the meter ------------------------- */

  var humNode = hero.querySelector("[data-humidity]");
  var humFill = hero.querySelector("[data-humidity-fill]");
  var humidity = 44;

  if (humNode) {
    tick({
      first: 9000,
      period: function () {
        return rand(9000, 14000);
      },
      step: function () {
        var next = humidity + (Math.random() < 0.5 ? -1 : 1);
        if (next < 41 || next > 47) next = humidity - (next - humidity);
        humidity = next;
        reveal(humNode, function () {
          humNode.textContent = String(humidity);
        });
        if (humFill) humFill.style.setProperty("--v", humidity + "%");
      }
    });
  }

  /* ---- Front door: opens, then closes again ------------------------------ */

  var door = hero.querySelector("[data-door]");

  if (door && !reduced.matches) {
    var doorState = door.querySelector(".device__reading--state");
    var doorStatus = door.querySelector("[data-door-status]");
    var doorNote = door.querySelector("[data-door-note]");
    var doorIcon = door.querySelector("[data-door-icon] use");

    var paintDoor = function (open) {
      door.classList.toggle("is-open", open);
      if (doorState) {
        doorState.setAttribute("data-i18n", open ? "w.door.open" : "w.door.closed");
      }
      if (doorNote) {
        doorNote.setAttribute("data-i18n", open ? "w.door.noteOpen" : "w.door.note");
      }
      if (doorStatus) {
        doorStatus.className = "status " + (open ? "status--idle" : "status--online");
      }
      if (doorIcon) doorIcon.setAttribute("href", open ? "#i-door" : "#i-lock");
      if (i18n) i18n.apply(door);
    };

    script.push({
      hold: 2400,
      show: function () {
        paintDoor(true);
      },
      hide: function () {
        paintDoor(false);
      }
    });
  }

  /* ---- Basement: the leak notification ----------------------------------- */

  var leak = hero.querySelector("[data-leak]");

  if (leak && !reduced.matches) {
    script.push({
      hold: 4500,
      show: function () {
        leak.classList.add("is-on");
      },
      hide: function () {
        leak.classList.remove("is-on");
      }
    });
  }

  /* ---- Hub: loses the link, then gets it back ---------------------------- */

  var strip = hero.querySelector("[data-link]");

  if (strip && !reduced.matches) {
    var stripText = strip.querySelector("[data-link-text]");
    var connectedTimer = null;

    var paintLink = function (state) {
      strip.classList.toggle("is-on", state !== "off");
      strip.classList.toggle("is-connected", state === "connected");
      if (stripText) {
        stripText.setAttribute(
          "data-i18n",
          state === "connected" ? "w.link.connected" : "w.link.reconnecting"
        );
        if (i18n) i18n.apply(strip);
      }
    };

    script.push({
      hold: 3600,
      show: function () {
        paintLink("reconnecting");
        /* Amber first, then it comes back green just before it slides away. */
        connectedTimer = window.setTimeout(function () {
          paintLink("connected");
        }, 2000);
      },
      hide: function () {
        window.clearTimeout(connectedTimer);
        strip.classList.remove("is-on");
        /* Hold the green until it is out of sight, then reset the color. */
        window.setTimeout(function () {
          if (!strip.classList.contains("is-on")) paintLink("off");
        }, 400);
      }
    });
  }

  if (script.length) runner();

  /* ---- Clocks ------------------------------------------------------------ */

  /* Beats run only when the hero is properly in view and the tab is in front. */
  var running = null;
  var showing = false; /* is the hero properly in view */

  function sync() {
    var next = !document.hidden && showing;
    if (next === running) return;
    running = next;
    hero.setAttribute("data-beats", next ? "on" : "off");
    for (var i = 0; i < beats.length; i++) {
      if (next) beats[i].start();
      else beats[i].stop();
    }
  }

  /* Showing = over 40% of the hero, or of the screen when the hero is the taller one. */
  function judge(entry) {
    if (!entry.rootBounds) return;
    showing =
      entry.intersectionRect.height >
      Math.min(entry.boundingClientRect.height, entry.rootBounds.height) * 0.4;
    sync();
  }

  document.addEventListener("visibilitychange", sync);

  if ("IntersectionObserver" in window) {
    /* Observer, not scroll math (forced reflow); a ladder tracks the moving threshold. */
    var rungs = [];
    for (var step = 0; step < 1; step += 0.05) rungs.push(step);
    rungs.push(1);

    new window.IntersectionObserver(function (entries) {
      judge(entries[entries.length - 1]);
    }, { threshold: rungs }).observe(hero);
  } else {
    /* No observer: measure by hand, batched into a frame. */
    var queued = false;

    var measure = function () {
      queued = false;
      var box = hero.getBoundingClientRect();
      var seen =
        Math.min(box.bottom, window.innerHeight) - Math.max(box.top, 0);
      showing = seen > Math.min(box.height, window.innerHeight) * 0.4;
      sync();
    };

    var measureSoon = function () {
      if (queued) return;
      queued = true;
      window.requestAnimationFrame(measure);
    };

    window.addEventListener("scroll", measureSoon, { passive: true });
    window.addEventListener("resize", measureSoon);
    measure();
  }

  /* Only the temperature needs a manual repaint; everything else is keyed for i18n. */
  document.addEventListener("halo:langchange", paintTemp);

  sync();
})(window, document);

/* ---- js/calc.js ---- */
/* Calc — three disclosed questions costed into a price range, ending in a mailto:. */

(function (window, document) {
  "use strict";

  var section = document.querySelector(".calc");
  if (!section) return;

  var console_ = section.querySelector("[data-calc]");
  if (!console_) return;

  var i18n = window.Halo && window.Halo.i18n;
  var t = i18n
    ? i18n.t
    : function (key) {
        return key;
      };

  var MAIL = "hello@yoursmarthome.com";
  var STEPS = 3;

  /* ---- The price list ------------------------------------------------------ */

  /* Hardware per device before tax, as [floor, ceiling]; the pairs make it a range. */
  var PRICES = {
    hub: [180, 180], /* one per home, always */
    contact: [30, 30], /* door and window sensor */
    lock: [80, 280],
    camera: [50, 220],
    leak: [22, 22],
    garage: [40, 40],
    thermostat: [250, 250], /* one per home */
    temp: [22, 22], /* room temperature sensor */
    control: [50, 120], /* light switch */
    bulb: [25, 150], /* color bulb or LED strip */
    blind: [50, 50],
    lawn: [50, 50], /* watering controller, one per garden */
    valve: [80, 80] /* one per watering zone */
  };

  /* Fitting, commissioning and handover, on top of the hardware. */
  var WORK = 0.3;
  var ROUND_TO = 10;

  /* ---- What is in a home ---------------------------------------------------- */

  /* What the footprint answers for the visitor. doors/temp/lights seed the sliders. */
  var HOMES = {
    flat: {
      doors: 1, temp: 2, lights: 3,
      windows: 4, cameras: 1, leaks: 2, garages: 0, blinds: 3
    },
    town: {
      doors: 2, temp: 3, lights: 5,
      windows: 7, cameras: 2, leaks: 3, garages: 1, blinds: 5
    },
    house: {
      doors: 3, temp: 5, lights: 8,
      windows: 11, cameras: 4, leaks: 4, garages: 2, blinds: 8,
      zones: 4 /* watering zones, and the only line a flat never has */
    }
  };

  /* The lawn is the one question the footprint asks rather than a goal. */
  var LAWN_HOME = "house";

  /* Markup order, not click order: the same answers must name the package the same. */
  var GOAL_ORDER = ["security", "climate", "light"];

  /* Slider per goal, so a goal nobody picked takes its question off the page. */
  var GOAL_REFINE = {
    security: "doors",
    climate: "temp",
    light: "lights"
  };

  /* ---- The console's pieces ---------------------------------------------- */

  var progress = console_.querySelector("[data-calc-progress]");
  var counter = console_.querySelector("[data-calc-count]");
  var stepOut = console_.querySelector("[data-calc-step]");
  var leftOut = console_.querySelector("[data-calc-left]");
  var ticks = console_.querySelectorAll(".calc__tick[data-tick]");

  var panels = {};
  var found = console_.querySelectorAll("[data-calc-panel]");
  for (var p = 0; p < found.length; p++) {
    panels[found[p].getAttribute("data-calc-panel")] = found[p];
  }

  var nav = console_.querySelector("[data-calc-nav]");
  var back = console_.querySelector("[data-calc-back]");
  var next = console_.querySelector("[data-calc-next]");

  var lowOut = console_.querySelector("[data-calc-low]");
  var highOut = console_.querySelector("[data-calc-high]");
  var toOut = console_.querySelector("[data-calc-to]");
  var spanOut = console_.querySelector("[data-calc-span]");
  var pkgOut = console_.querySelector("[data-calc-pkg]");
  var homeOut = console_.querySelector("[data-calc-home]");
  var billOut = console_.querySelector("[data-calc-bill]");
  var mailOut = console_.querySelector("[data-calc-mail]");
  var restart = console_.querySelector("[data-calc-restart]");

  var goalInputs = console_.querySelectorAll("[data-goal]");
  var homeInputs = console_.querySelectorAll("[data-home]");
  var lawnInput = console_.querySelector("[data-lawn]");
  var sliders = console_.querySelectorAll("[data-refine-in]");

  if (!panels["1"] || !panels["2"] || !panels["3"] || !panels.result) return;

  /* ---- State -------------------------------------------------------------- */

  var view = 1; /* 1, 2, 3 — or "result" */
  var home = null;
  var touched = {}; /* sliders moved by hand; the rest still follow the home */

  function goals() {
    var picked = [];
    for (var i = 0; i < GOAL_ORDER.length; i++) {
      var input = console_.querySelector('[data-goal="' + GOAL_ORDER[i] + '"]');
      if (input && input.checked) picked.push(GOAL_ORDER[i]);
    }
    return picked;
  }

  function chose(goal) {
    return goals().indexOf(goal) !== -1;
  }

  function count(name) {
    var input = console_.querySelector('[data-refine-in="' + name + '"]');
    return input ? Number(input.value) : 0;
  }

  function watering() {
    return home === LAWN_HOME && !!lawnInput && lawnInput.checked;
  }

  /* ---- The bill ------------------------------------------------------------- */

  /* Both figures and the printed lines read this one list, so they cannot disagree. */
  function bill() {
    var plan = HOMES[home] || HOMES.flat;
    var lines = [{ item: "hub", n: 1 }];

    if (chose("security")) {
      var doors = count("doors");
      lines.push({ item: "contact", n: doors + plan.windows });
      lines.push({ item: "lock", n: doors });
      lines.push({ item: "camera", n: plan.cameras });
      lines.push({ item: "leak", n: plan.leaks });
      if (plan.garages) lines.push({ item: "garage", n: plan.garages });
    }

    if (chose("climate")) {
      lines.push({ item: "thermostat", n: 1 });
      lines.push({ item: "temp", n: count("temp") });
    }

    if (chose("light")) {
      var rooms = count("lights");
      lines.push({ item: "control", n: rooms });
      lines.push({ item: "bulb", n: rooms });
      lines.push({ item: "blind", n: plan.blinds });
    }

    if (watering()) {
      lines.push({ item: "lawn", n: 1 });
      lines.push({ item: "valve", n: plan.zones });
    }

    return lines;
  }

  /* Every line at its floor, then at its ceiling, with the same work % on both. */
  function estimate() {
    var lines = bill();
    var low = 0;
    var high = 0;

    for (var i = 0; i < lines.length; i++) {
      var price = PRICES[lines[i].item];
      low += price[0] * lines[i].n;
      high += price[1] * lines[i].n;
    }

    return {
      low: round(low * (1 + WORK)),
      high: round(high * (1 + WORK))
    };
  }

  function round(value) {
    return Math.round(value / ROUND_TO) * ROUND_TO;
  }

  /* Dollars in both languages — the email must read the same whichever wrote it. */
  function money(value) {
    return "$" + String(value).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  }

  /* The range as one string. An all-fixed-price job is one figure, not "$620–$620". */
  function range() {
    var sum = estimate();
    return sum.low === sum.high
      ? money(sum.low)
      : money(sum.low) + "–" + money(sum.high);
  }

  /* ---- What to call it ---------------------------------------------------- */

  function packageName() {
    var picked = goals();
    if (picked.length === GOAL_ORDER.length) return t("calc.pkg.all");

    var names = [];
    for (var i = 0; i < picked.length; i++) names.push(t("calc.pkg." + picked[i]));
    return names.join(t("calc.pkg.join"));
  }

  function homeName() {
    return home ? t("calc.home." + home + ".full") : "";
  }

  /* ---- The letter --------------------------------------------------------- */

  /* Subject and body in a mailto:; nothing is posted, the mail client is the form. */
  function letter() {
    var span = range();

    var subject = fill(t("calc.mail.subject"), { range: span });
    var body = fill(t("calc.mail.body"), {
      package: packageName(),
      home: homeName(),
      range: span
    });

    return (
      "mailto:" +
      MAIL +
      "?subject=" +
      encodeURIComponent(subject) +
      "&body=" +
      encodeURIComponent(body)
    );
  }

  /* Named placeholders, so a translation can reorder them without touching this. */
  function fill(template, values) {
    return String(template).replace(/\{(\w+)\}/g, function (whole, key) {
      return Object.prototype.hasOwnProperty.call(values, key)
        ? values[key]
        : whole;
    });
  }

  /* ---- Painting ----------------------------------------------------------- */

  function paintProgress() {
    var done = view === "result";
    var step = done ? STEPS : view;

    /* On the result the full rail says it; the counter would only repeat the title. */
    if (counter) counter.hidden = done;
    if (stepOut) stepOut.textContent = fill(t("calc.step"), { n: step, of: STEPS });
    if (leftOut) leftOut.textContent = t("calc.left." + (STEPS - step));

    for (var i = 0; i < ticks.length; i++) {
      var n = Number(ticks[i].getAttribute("data-tick"));
      var state = "next";
      if (done || n < step) state = "done";
      else if (n === step) state = "now";
      ticks[i].setAttribute("data-state", state);
    }
  }

  function paintPanels() {
    var keys = ["1", "2", "3", "result"];
    for (var i = 0; i < keys.length; i++) {
      panels[keys[i]].hidden = String(view) !== keys[i];
    }
  }

  /* A question per chosen goal only. The lawn is about the plot, so the home asks it. */
  function paintRefines() {
    for (var i = 0; i < GOAL_ORDER.length; i++) {
      var row = console_.querySelector(
        '[data-refine="' + GOAL_REFINE[GOAL_ORDER[i]] + '"]'
      );
      if (row) row.hidden = !chose(GOAL_ORDER[i]);
    }

    var lawn = console_.querySelector('[data-refine="lawn"]');
    if (lawn) lawn.hidden = home !== LAWN_HOME;
  }

  function paintNav() {
    if (!nav) return;
    nav.hidden = view === "result";
    if (view === "result") return;

    back.hidden = view === 1;
    next.textContent = t(view === STEPS ? "calc.see" : "calc.next");

    var ready = view === 1 ? goals().length > 0 : view === 2 ? !!home : true;
    next.disabled = !ready;
  }

  function paintResult() {
    if (view !== "result") return;

    var sum = estimate();
    var one = sum.low === sum.high;
    if (lowOut) lowOut.textContent = money(sum.low);
    if (highOut) {
      highOut.textContent = money(sum.high);
      highOut.hidden = one;
    }
    if (spanOut) spanOut.hidden = one;
    if (toOut) toOut.hidden = one;
    if (pkgOut) pkgOut.textContent = packageName();
    if (homeOut) homeOut.textContent = homeName();
    if (mailOut) mailOut.setAttribute("href", letter());

    if (billOut) {
      billOut.textContent = "";
      var lines = bill();
      for (var i = 0; i < lines.length; i++) {
        billOut.appendChild(
          billLine(t("calc.item." + lines[i].item), "× " + lines[i].n)
        );
      }
      /* The work is the last bill line, and the one that shows a % rather than a count. */
      var work = billLine(
        t("calc.item.work"),
        "+" + Math.round(WORK * 100) + "%"
      );
      work.className = "calc__bill-work";
      billOut.appendChild(work);
    }
  }

  function billLine(name, value) {
    var item = document.createElement("li");

    var left = document.createElement("span");
    left.className = "calc__bill-name";
    left.textContent = name;

    var right = document.createElement("span");
    right.className = "mono calc__bill-count";
    right.textContent = value;

    item.appendChild(left);
    item.appendChild(right);
    return item;
  }

  function paint() {
    paintProgress();
    paintPanels();
    paintNav();
    paintResult();
  }

  /* ---- Getting about ------------------------------------------------------ */

  function go(to, moved) {
    view = to;
    if (view === 3) paintRefines();
    paint();
    if (moved) focusPanel();
  }

  /* The arriving panel takes focus — but only on a move, or load would jump here. */
  /* Focus after the paint: focusing a just-unhidden panel forces a synchronous reflow. */
  function focusPanel() {
    var panel = panels[String(view)];
    if (!panel) return;
    var title = panel.querySelector(".calc__panel-title");
    if (!title) return;
    window.setTimeout(function () {
      title.focus();
    }, 0);
  }

  /* ---- Sliders ------------------------------------------------------------ */

  /* The track's fill is a custom property, the same as the design system's. */
  function paintSlider(input) {
    var min = Number(input.min || 0);
    var max = Number(input.max || 100);
    var pct = ((Number(input.value) - min) / (max - min)) * 100;
    input.style.setProperty("--fill", pct + "%");

    var name = input.getAttribute("data-refine-in");
    var out = console_.querySelector('[data-refine-out="' + name + '"]');
    if (out) {
      out.textContent =
        Number(input.value) === Number(max) ? input.value + "+" : input.value;
    }
  }

  /* Untouched counts follow the home, so the footprint can answer step three. */
  function seedCounts() {
    if (!home) return;
    for (var i = 0; i < sliders.length; i++) {
      var name = sliders[i].getAttribute("data-refine-in");
      if (touched[name]) continue;
      sliders[i].value = HOMES[home][name];
      paintSlider(sliders[i]);
    }
  }

  /* ---- Wiring -------------------------------------------------------------- */

  for (var g = 0; g < goalInputs.length; g++) {
    goalInputs[g].addEventListener("change", function () {
      paintNav();
    });
  }

  for (var h = 0; h < homeInputs.length; h++) {
    homeInputs[h].addEventListener("change", function (event) {
      home = event.target.getAttribute("data-home");
      seedCounts();
      /* A flat is never asked about a lawn, so an earlier answer is not one any more. */
      if (home !== LAWN_HOME && lawnInput) lawnInput.checked = false;
      paintNav();
    });
  }

  for (var s = 0; s < sliders.length; s++) {
    paintSlider(sliders[s]);
    sliders[s].addEventListener("input", function (event) {
      touched[event.target.getAttribute("data-refine-in")] = true;
      paintSlider(event.target);
    });
  }

  if (next) {
    next.addEventListener("click", function () {
      if (next.disabled) return;
      go(view === STEPS ? "result" : view + 1, true);
    });
  }
  if (back) {
    back.addEventListener("click", function () {
      go(view === 1 ? 1 : view - 1, true);
    });
  }
  if (restart) {
    restart.addEventListener("click", function () {
      go(1, true);
    });
  }

  /* The estimate and its mailto: have no i18n key, so they are rebuilt by hand. */
  document.addEventListener("halo:langchange", function () {
    paint();
  });

  /* All the script-only parts come on together; without one it stays a plain form. */
  if (progress) progress.hidden = false;
  if (nav) nav.hidden = false;
  console_.setAttribute("data-calc", "live");
  go(1);
})(window, document);
