#!/bin/sh
# Concatenates the stylesheets and scripts into one bundle each, then inlines the
# CSS into the pages: a page costs one request instead of eleven. Sources stay
# authored a file per layer.
#
#   ./build.sh          rebuild the bundles, inline the CSS, restamp ?v=
#   ./build.sh --check  exit 1 if the bundles or pages are stale (for CI / pre-commit)
#
# Order is load-bearing: palette before semantic before the rest, and i18n
# before every script that reads window.Halo.

set -eu

cd "$(dirname "$0")"

CSS_SOURCES="css/tokens/palette.css css/tokens/semantic.css css/base.css css/components.css css/sections.css"
JS_SOURCES="js/i18n.js js/reveal.js js/problem.js js/plan.js js/hero.js js/calc.js"

PAGES="index.html privacy.html"

# The stylesheet has no committed bundle: it exists only inside the pages, so a
# file on disk would be a second copy nothing loads and every CSS edit would show
# up twice in a diff.
JS_BUNDLE="js/halo.js"

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

# The srcset ladder. Separate from the default build because it needs cwebp and
# only changes when the photograph does — the rungs are committed like the bundles.
if [ "${1:-}" = "--images" ]; then
  command -v cwebp >/dev/null || { echo "need cwebp (brew install webp)" >&2; exit 1; }
  for w in 480 800 1144 1600; do
    cwebp -quiet -q 82 -resize "$w" 0 assets/appartment.webp -o "assets/appartment-$w.webp"
    printf 'assets/appartment-%s.webp  %7s bytes\n' "$w" "$(wc -c < "assets/appartment-$w.webp" | tr -d ' ')"
  done
  echo "the 2000w rung is assets/appartment.webp itself — not regenerated"
  exit 0
fi

# Sources are concatenated verbatim, not minified. Pages are served gzipped, which
# already collapses the whitespace and repetition a minifier would; a hand-rolled
# one buys a few kB and risks mangling a selector or an ASI-sensitive line.
bundle() {
  out=$1
  shift
  printf '/* Generated by build.sh — edit the sources, not this file. */\n' > "$out"
  for src in "$@"; do
    printf '\n/* ---- %s ---- */\n' "$src" >> "$out"
    cat "$src" >> "$out"
  done
}

hash_of() {
  cat "$@" | shasum -a 256 | cut -c1-8
}

# Rewrites a page: the stylesheet goes inside the css:inline markers, and the
# script URL gets the current stamp. Reads $1, writes $2 — never in place.
#
# The query string is what makes a long Cache-Control safe: a new build is a new
# URL. GitHub Pages caps at 10 minutes today, so this only matters behind a CDN.
render() {
  # Both markers must be self-contained one-line comments. An opener still hanging
  # open would comment out the stylesheet it introduces, and the page would render
  # unstyled with nothing to show for it — so refuse rather than emit that.
  grep -q '<!-- css:inline.*-->' "$1" && grep -q '<!-- /css:inline -->' "$1" || {
    echo "$1: css:inline markers missing or not one-line comments" >&2
    return 1
  }

  awk -v css="$3" '
    index($0, "<!-- css:inline") {
      print
      print "    <style>"
      while ((getline line < css) > 0) print line
      close(css)
      print "    </style>"
      inside = 1
      next
    }
    index($0, "<!-- /css:inline -->") { inside = 0 }
    !inside
  ' "$1" | sed "s|halo\.js?v=[A-Za-z0-9]*|halo.js?v=$version|g" > "$2"
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

bundle "$tmp/halo.css" $CSS_SOURCES
bundle "$tmp/halo.js" $JS_SOURCES

# The CSS rides inside the pages now, so only the script has a URL to bust.
version=$(hash_of "$tmp/halo.js")

if [ "$check_only" -eq 1 ]; then
  status=0
  if [ ! -f "$JS_BUNDLE" ] || ! cmp -s "$JS_BUNDLE" "$tmp/halo.js"; then
    echo "stale: $JS_BUNDLE (run ./build.sh)" >&2
    status=1
  fi
  # A page is current when re-rendering it changes nothing — one comparison that
  # covers both the inlined stylesheet and the stamp.
  for page in $PAGES; do
    if ! render "$page" "$tmp/page" "$tmp/halo.css" || ! cmp -s "$page" "$tmp/page"; then
      echo "stale: $page (run ./build.sh)" >&2
      status=1
    fi
  done
  [ "$status" -eq 0 ] && echo "bundle and pages are current (v=$version)"
  exit "$status"
fi

cp "$tmp/halo.js" "$JS_BUNDLE"

for page in $PAGES; do
  render "$page" "$tmp/page" "$tmp/halo.css" && cp "$tmp/page" "$page"
done

printf 'stylesheet    %6s bytes  (%s, inlined into the pages)\n' "$(wc -c < "$tmp/halo.css" | tr -d ' ')" "$(echo $CSS_SOURCES | wc -w | tr -d ' ') files"
printf 'js/halo.js    %6s bytes  (%s)\n' "$(wc -c < "$JS_BUNDLE" | tr -d ' ')" "$(echo $JS_SOURCES | wc -w | tr -d ' ') files"
for page in $PAGES; do
  printf '%-12s  %6s bytes\n' "$page" "$(wc -c < "$page" | tr -d ' ')"
done
printf 'stamped ?v=%s into %s\n' "$version" "$PAGES"
