#!/bin/sh
# Concatenates the stylesheets and scripts into one bundle each, so a page costs
# two requests instead of eleven. Sources stay authored a file per layer.
#
#   ./build.sh          rebuild css/halo.css and js/halo.js, restamp ?v=
#   ./build.sh --check  exit 1 if the bundles are stale (for CI / pre-commit)
#
# Order is load-bearing: palette before semantic before the rest, and i18n
# before every script that reads window.Halo.

set -eu

cd "$(dirname "$0")"

CSS_SOURCES="css/tokens/palette.css css/tokens/semantic.css css/base.css css/components.css css/sections.css"
JS_SOURCES="js/i18n.js js/reveal.js js/problem.js js/plan.js js/hero.js js/calc.js"

PAGES="index.html privacy.html"

CSS_BUNDLE="css/halo.css"
JS_BUNDLE="js/halo.js"

check_only=0
[ "${1:-}" = "--check" ] && check_only=1

# The srcset ladder. Separate from the default build because it needs cwebp and
# only changes when the photograph does — the rungs are committed like the bundles.
if [ "${1:-}" = "--images" ]; then
  command -v cwebp >/dev/null || { echo "need cwebp (brew install webp)" >&2; exit 1; }
  for w in 480 800 1144 1600; do
    cwebp -quiet -q 82 -resize "$w" 0 assets/appartment.webp -o "assets/appartment-$w.webp"
    printf 'assets/appartment-%s.webp  %7s bytes\n' "$w" "$(wc -c < "assets/appartment-$w.webp" | tr -d ' ')"
  done
  echo "the 2000w rung is assets/appartment.webp itself — not regenerated"
  exit 0
fi

# Sources are concatenated verbatim, not minified. Pages are served gzipped, which
# already collapses the whitespace and repetition a minifier would; a hand-rolled
# one buys a few kB and risks mangling a selector or an ASI-sensitive line.
bundle() {
  out=$1
  shift
  printf '/* Generated by build.sh — edit the sources, not this file. */\n' > "$out"
  for src in "$@"; do
    printf '\n/* ---- %s ---- */\n' "$src" >> "$out"
    cat "$src" >> "$out"
  done
}

hash_of() {
  cat "$@" | shasum -a 256 | cut -c1-8
}

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

bundle "$tmp/halo.css" $CSS_SOURCES
bundle "$tmp/halo.js" $JS_SOURCES

version=$(hash_of "$tmp/halo.css" "$tmp/halo.js")

if [ "$check_only" -eq 1 ]; then
  status=0
  for pair in "$CSS_BUNDLE:$tmp/halo.css" "$JS_BUNDLE:$tmp/halo.js"; do
    built=${pair%%:*}
    fresh=${pair#*:}
    if [ ! -f "$built" ] || ! cmp -s "$built" "$fresh"; then
      echo "stale: $built (run ./build.sh)" >&2
      status=1
    fi
  done
  for page in $PAGES; do
    if ! grep -q "halo\.css?v=$version" "$page"; then
      echo "stale: $page is not stamped ?v=$version (run ./build.sh)" >&2
      status=1
    fi
  done
  [ "$status" -eq 0 ] && echo "bundles are current (v=$version)"
  exit "$status"
fi

cp "$tmp/halo.css" "$CSS_BUNDLE"
cp "$tmp/halo.js" "$JS_BUNDLE"

# The query string is what makes a long Cache-Control safe: a new build is a new
# URL. GitHub Pages caps at 10 minutes today, so this only matters behind a CDN.
for page in $PAGES; do
  sed -e "s|halo\.css?v=[A-Za-z0-9]*|halo.css?v=$version|g" \
      -e "s|halo\.js?v=[A-Za-z0-9]*|halo.js?v=$version|g" \
      "$page" > "$tmp/page" && cp "$tmp/page" "$page"
done

printf 'css/halo.css  %6s bytes  (%s)\n' "$(wc -c < "$CSS_BUNDLE" | tr -d ' ')" "$(echo $CSS_SOURCES | wc -w | tr -d ' ') files"
printf 'js/halo.js    %6s bytes  (%s)\n' "$(wc -c < "$JS_BUNDLE" | tr -d ' ')" "$(echo $JS_SOURCES | wc -w | tr -d ' ') files"
printf 'stamped ?v=%s into %s\n' "$version" "$PAGES"
